#!/bin/bash

set -e

if [[ -f $HOME/.config/gh-access-token ]]; then
  GITHUB_ACCESS_TOKEN=$(cat $HOME/.config/gh-access-token)
fi

: ${GITHUB_ACCESS_TOKEN:?"Please set your GitHub access token"}

docker run -ti --rm \
           -v `pwd`:/project \
           -w /project \
           -e GITHUB_ACCESS_TOKEN="${GITHUB_ACCESS_TOKEN}" \
           fgrehm/gh-release \
           $*
